console.log("Hello Javascript");
var firstName = "Thang";
console.log(firstName);
let x;
let y;
let z = 2;
let t = 2;
x = 5;
y = x++;
z += x;
t **= x;
console.log(x);
console.log(y);
console.log(z);
console.log(t);